---
title: "Cross-sectional incidence estimation with multiple subtypes"
author: "Qi Wang"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
if(!require(XSRecency)){
  devtools::install("/Users/qi/Desktop/GitHub/HIV-incidence-recency-heterogeneity/XSRecency-pt-functions") 
}
```

```{r}
library(XSRecency)
library(geepack)
library(data.table)
library(dplyr)
YEAR2DAY=365.25

get.phi.function = function(window.period, shadow.period, phi_tfrr = NULL, 
                            phi_frr = NULL, phi_norm_mu = NULL, phi_norm_sd = NULL, 
                            phi_norm_div = NULL, phi_pnorm_mu = NULL, phi_pnorm_sd = NULL, 
                            phi_pnorm_div = NULL){
  # Get the gamma parameters and baseline phi function
  params = get.gamma.params(window=window.period/YEAR2DAY, shadow=shadow.period/YEAR2DAY)
  # Set up each type of phi function, will be overwritten
  phi.none = function(t) 1-pgamma(t, shape = params[1], rate = params[2])
  phi.const = function(t) 1-pgamma(t, shape = params[1], rate = params[2])
  phi.norm = function(t) 1-pgamma(t, shape = params[1], rate = params[2])
  phit.pnorm = function(t) 1-pgamma(t, shape = params[1], rate = params[2])
  
  phi.func = phi.none
  
  # Get the phi function with constant FRR either past a certain time
  # or fixed after it hits some value.
  if(!is.null(phi_tfrr) | !is.null(phi_frr)){
    if(!is.null(phi_tfrr)){
      ttime = phi_tfrr
      tval = phi.none(ttime)
    }
    if(!is.null(phi_frr)){
      tau = 12
      tval = phi_frr
      ttime = uniroot(function(t) phi.none(t) - tval, interval=c(0, tau))$root
      cat(ttime)
    }
    phi.const = function(t, ...) phi.none(t)*(t <= ttime) + tval*(t > ttime)
    phi.func = phi.const
  }
  if(!is.null(phi_norm_mu)){
    phi.norm = function(t) phi.const(t) + dnorm(t-phi_norm_mu, mean=0, sd=phi_norm_sd) / phi_norm_div
    phi.func = phi.norm
  }
  if(!is.null(phi_pnorm_mu)){
    phi.pnorm = function(t) phi.const(t) + pnorm(t-phi_pnorm_mu, mean=0, sd=phi_pnorm_sd) / phi_pnorm_div
    phi.func = phi.pnorm
  }
  return(phi.func)
}


simulate_beta_study = function(n_long_infect, phi.func, minT, maxT){
  N = n_long_infect

  inf_times = runif(n=N, min=minT, max=maxT)
  recent = rbinom(n=N, size=1, p=phi.func(inf_times))
  
  beta_study = data.frame(inf_times=inf_times, recent=recent)
  return(beta_study)
}


simulate_beta_studies = function(nsims, n_long_infect, phi.func, minT, maxT){
  beta_studies = replicate(nsims, simulate_beta_study(n_long_infect, phi.func, minT, maxT),
                           simplify = FALSE)
  
  return(beta_studies)
}
```


```{r}
get_panel_data = function(n_sims, sample_size_screen, profiles_screen, 
                          infection.function, bigT){
  # Within a column: number of observations of each group of individuals generated by
  # multinomial distribution
  # Different columns are different replications
  num_obs_screen = rmultinom(n_sims, size = sample_size_screen, prob = profiles_screen$Proportion)
  out_panel_datalist = vector("list", length = nrow(profiles_screen))
  for(i in 1:nrow(profiles_screen)){
    cat("\nGenerating ", i, "th group:\n")
    group_incid_screen = profiles_screen$Incidence[i]
    group_preval_screen = profiles_screen$Prevalence[i]
    group_propor_screen = profiles_screen$Proportion[i]
    phi.function = get.phi.function(profiles_screen$Window[i], profiles_screen$Shadow[i], phi_frr = profiles_screen$FRR[i])
    
    group_panel_datalist = vector("list", length = n_sims)
    for(j in 1:n_sims){
      if(j %% 200 == 0){
        cat("Generating", j, "th replication\n")
      }
      group_num_obs_screen = num_obs_screen[i, j]
      group_panel_data = generate.data(1, group_num_obs_screen, infection.function = infection.function, baseline_incidence = group_incid_screen, prevalence = group_preval_screen, rho = NA, phi.func = phi.function, times = 0, summarize = FALSE)[, c("pos", "rpos")]
      group_panel_data$sim = j
      
      group_panel_datalist[[j]] = group_panel_data
      if(j %% 200 == 0){
        cat("\n")
      }
    }
    group_panel_nsims = data.table::rbindlist(group_panel_datalist)
    group_panel_nsims$Subtype = profiles_screen$Subtype[i]
    out_panel_datalist[[i]] = group_panel_nsims
  }
  out_panel_data = data.table::rbindlist(out_panel_datalist)
  
  return(out_panel_data)
}
```

```{r}
library(foreach)
set.seed(1024)
profiles_screen = data.frame(Subtype = c(1,2), Proportion = c(0.5, 0.5),
                             Incidence = c(0.05, 0.02), Prevalence = c(0.15, 0.25),
                             Window = c(176, 186), Shadow = c(95.72, 203.29),
                             FRR = c(1e-10, 0.026))
true_incid = sum(profiles_screen$Proportion * profiles_screen$Incidence)
infection.function = infections.con
bigT = 2
n_sims = 500
sample_size = 2500
n_bootstrap = 500
panel = get_panel_data(n_sims, sample_size, profiles_screen, infection.function, bigT)

n_long_infect = 1500
phi.func1 = get.phi.function(profiles_screen$Window[1], profiles_screen$Shadow[1], phi_frr = profiles_screen$FRR[1])
phi.func2 = get.phi.function(profiles_screen$Window[2], profiles_screen$Shadow[2], phi_frr = profiles_screen$FRR[2])
beta1_studies = simulate_beta_studies(n_sims, n_long_infect, phi.func1, minT = bigT, maxT = 12)
betas1 = sapply(beta1_studies, function(study){
  N = nrow(study)
  beta = sum(study$recent) / N
  beta_var = beta * (1 - beta) / N
  return(list(beta=beta, beta_var=beta_var))
})
beta1_ests = unlist(betas1["beta",])
beta1_vars = unlist(betas1["beta_var",])

omega1_studies = simulate_studies(n_sims, phi.func1)
omega1_studies = sapply(omega1_studies, function(study){
  setnames(study, c("id", "ui", "ri"))
  study[study$ui == 0, "ui"] = 0.01
  study = study[which(study$ui <= 2), ]
  return(study)
}, simplify = FALSE)

omegas1 = sapply(omega1_studies, function(study){
  estimate.phi(phidat=study, maxT=bigT, bigT=bigT, min_dt=TRUE,
               formula="ri ~ poly(log(ui), raw=T, degree=4)", family=binomial(link="logit"),
               use_geese=TRUE, plot_phi=FALSE)
})

omega1_ests = unlist(omegas1["omega",])
omega1_vars = unlist(omegas1["omega_var",])

beta2_studies = simulate_beta_studies(n_sims, n_long_infect, phi.func2, minT = bigT, maxT = 12)
betas2 = sapply(beta2_studies, function(study){
  N = nrow(study)
  beta = sum(study$recent) / N
  beta_var = beta * (1 - beta) / N
  return(list(beta=beta, beta_var=beta_var))
})
beta2_ests = unlist(betas2["beta",])
beta2_vars = unlist(betas2["beta_var",])

omega2_studies = simulate_studies(n_sims, phi.func2)
omega2_studies = sapply(omega2_studies, function(study){
  setnames(study, c("id", "ui", "ri"))
  study[study$ui == 0, "ui"] = 0.01
  study = study[which(study$ui <= 2), ]
  return(study)
}, simplify = FALSE)

omegas2 = sapply(omega2_studies, function(study){
  estimate.phi(phidat=study, maxT=bigT, bigT=bigT, min_dt=TRUE,
               formula="ri ~ poly(log(ui), raw=T, degree=4)", family=binomial(link="logit"),
               use_geese=TRUE, plot_phi=FALSE)
})

omega2_ests = unlist(omegas2["omega",])
omega2_vars = unlist(omegas2["omega_var",])

# Proposed
incid_est1_vec = NULL
# Standard
incid_est2_vec = NULL

incid_est1_par_bs_ses = NULL
incid_est2_par_bs_ses = NULL

incid_est1_par_ci_cov = NULL
incid_est2_par_ci_cov = NULL
for(i in 1:n_sims){
  if(i %% 200 == 0){
    cat(i/n_sims,"\n")
  }
  panel_1sim = panel[which(panel$sim == i), ]
  beta1_est = beta1_ests[i]
  beta2_est = beta2_ests[i]
  omega1_est = omega1_ests[i]
  omega2_est = omega2_ests[i]
  beta1_var = beta1_vars[i]
  beta2_var = beta2_vars[i]
  omega1_var = omega1_vars[i]
  omega2_var = omega2_vars[i]
  
  pi_est1 = sum(panel_1sim$Subtype == 1) / nrow(panel_1sim)
  pi_est2 = 1 - pi_est1
  
  # Proposed
  panel_1sim_type1 = panel_1sim %>% filter(Subtype == 1)
  panel_1sim_type2 = panel_1sim %>% filter(Subtype == 2)
  m1_lambda_est1 = (sum(panel_1sim_type1$rpos, na.rm = TRUE) - sum(panel_1sim_type1$pos) * beta1_est) / 
    (sum(1 - panel_1sim_type1$pos) * (omega1_est - beta1_est * bigT) )
  m1_lambda_est2 = (sum(panel_1sim_type2$rpos, na.rm = TRUE) - sum(panel_1sim_type2$pos) * beta2_est) / 
    (sum(1 - panel_1sim_type2$pos) * (omega2_est - beta2_est * bigT) )
  m1_lambda_est = m1_lambda_est1 * pi_est1 + m1_lambda_est2 * pi_est2
  incid_est1_vec[i] = m1_lambda_est
  
  
  # Standard
  avg_beta_est = beta1_est * pi_est1 + beta2_est * pi_est2
  avg_omega_est = omega1_est * pi_est1 + omega2_est * pi_est2
  m3_lambda_est = (sum(panel_1sim$rpos, na.rm = TRUE) - sum(panel_1sim$pos) * avg_beta_est) /
    (sum(1 - panel_1sim$pos) * (avg_omega_est - avg_beta_est * bigT))
  incid_est2_vec[i] = m3_lambda_est
  
  incid_est1_bs_par_vec = NULL
  
  incid_est2_bs_par_vec = NULL
  for(j in 1:n_bootstrap){
    bs_beta1_est_par = 0
    bs_beta2_est_par = exp(rnorm(1, log(beta2_est), sqrt(beta2_var)/beta2_est))
    bs_omega1_est_par = exp(rnorm(1, log(omega1_est), sqrt(omega1_var)/omega1_est))
    bs_omega2_est_par = exp(rnorm(1, log(omega2_est), sqrt(omega2_var)/omega2_est))
    panel_bs = panel_1sim[sample(1:sample_size, sample_size, replace = TRUE), ]
    
    pi1_est_bs = sum(panel_bs$Subtype == 1) / nrow(panel_bs)
    pi2_est_bs = 1 - pi1_est_bs
  
    # Proposed
    panel_bs_type1 = panel_bs %>% filter(Subtype == 1)
    panel_bs_type2 = panel_bs %>% filter(Subtype == 2)
    
    m1_lambda1_est_par_bs = (sum(panel_bs_type1$rpos, na.rm = TRUE) - sum(panel_bs_type1$pos) * bs_beta1_est_par) / 
      (sum(1 - panel_bs_type1$pos) * (bs_omega1_est_par - bs_beta1_est_par * bigT) )
    m1_lambda2_est_par_bs = (sum(panel_bs_type2$rpos, na.rm = TRUE) - sum(panel_bs_type2$pos) * bs_beta2_est_par) / 
      (sum(1 - panel_bs_type2$pos) * (bs_omega2_est_par - bs_beta2_est_par * bigT) )
    incid_est1_bs_par_vec[j] = m1_lambda1_est_par_bs * pi1_est_bs + m1_lambda2_est_par_bs * pi2_est_bs
    
    
    # Standard
    avg_beta_est_par_bs = bs_beta1_est_par * pi1_est_bs + bs_beta2_est_par * pi2_est_bs
    avg_omega_est_par_bs = bs_omega1_est_par * pi1_est_bs + bs_omega2_est_par * pi2_est_bs
    m3_lambda_est_par_bs = (sum(panel_bs$rpos, na.rm = TRUE) - sum(panel_bs$pos) * avg_beta_est_par_bs) /
      (sum(1 - panel_bs$pos) * (avg_omega_est_par_bs - avg_beta_est_par_bs * bigT))
    incid_est2_bs_par_vec[j] = m3_lambda_est_par_bs
  }
  incid_est1_par_bs_ses[i] = sd(incid_est1_bs_par_vec)
  incid_est2_par_bs_ses[i] = sd(incid_est2_bs_par_vec)
  
  
  incid_est1_par_ci_cov[i] = as.integer(log(m1_lambda_est) - qnorm(0.975)*sd(log(incid_est1_bs_par_vec)) <= log(true_incid) & log(m1_lambda_est) + qnorm(0.975)*sd(log(incid_est1_bs_par_vec)) >= log(true_incid) & m1_lambda_est > 0 & (!is.na(sd(log(incid_est1_bs_par_vec)))))
  
  incid_est2_par_ci_cov[i] = as.integer(log(m3_lambda_est) - qnorm(0.975)*sd(log(incid_est2_bs_par_vec)) <= log(true_incid) & log(m3_lambda_est) + qnorm(0.975)*sd(log(incid_est2_bs_par_vec)) >= log(true_incid) & m3_lambda_est > 0 & (!is.na(sd(log(incid_est2_bs_par_vec)))))
}

true_incid
mean(incid_est1_vec)
mean(incid_est2_vec)
(mean(incid_est1_vec) - true_incid)
(mean(incid_est2_vec) - true_incid)
sd(incid_est1_vec)
sd(incid_est2_vec)

mean(incid_est1_par_bs_ses)
mean(incid_est2_par_bs_ses)

mean(incid_est1_par_ci_cov)
mean(incid_est2_par_ci_cov)
```